# Generated by Django 5.1.2 on 2024-11-06 01:49

import django.db.models.deletion
import django.utils.timezone
import pedidos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('confeitaria', '0008_alter_categorias_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_comprador', models.CharField(max_length=60)),
                ('contato_comprador', models.CharField(max_length=20)),
                ('data_retirada', models.DateField(default=pedidos.models.data_retirada_padrao)),
                ('mensagem', models.TextField(blank=True, max_length=255, null=True)),
                ('data_pedido', models.DateField(default=django.utils.timezone.now)),
                ('valor_total', models.FloatField(default=0.0)),
                ('entregue', models.BooleanField(default=False)),
                ('data_entrega', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('doce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confeitaria.doce')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='itens',
            field=models.ManyToManyField(through='pedidos.PedidoItem', to='confeitaria.doce'),
        ),
    ]
