# Generated by Django 5.1.2 on 2024-11-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='nome_retirada',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
