# Generated by Django 5.1.2 on 2024-11-06 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confeitaria', '0007_categorias_doce_estoque_alter_doce_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorias',
            options={'verbose_name': 'Categoria'},
        ),
    ]
