# Generated by Django 5.1.2 on 2024-11-06 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confeitaria', '0008_alter_categorias_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CATEGORIAS',
            new_name='Categoria',
        ),
    ]
